# ASP.NET Core (.NET Framework)
# Full pipeline with build, test (MSTest), and artifact creation

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# Ensure correct .NET SDK and tools
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
  displayName: 'Install .NET SDK'

# Restore NuGet packages
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
  displayName: 'Restore NuGet packages'

# Build the solution (includes web and test projects)
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: >
      /p:DeployOnBuild=true
      /p:WebPublishMethod=Package
      /p:PackageAsSingleFile=true
      /p:SkipInvalidConfigurations=true
      /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip"
      /p:DeployIisAppPath="Default Web Site"
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  displayName: 'Build Solution'

# Diagnostic: list build outputs to confirm test DLLs exist
- script: |
    echo "Listing build output directories..."
    dir "$(Build.SourcesDirectory)\**\bin\$(buildConfiguration)" /s /b
  displayName: 'List build outputs (debugging)'

# Run MSTest unit tests
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    diagnosticsEnabled: true
    searchFolder: '$(System.DefaultWorkingDirectory)'
    runInParallel: false
    otherConsoleOptions: '--blame'
  displayName: 'Run MSTest unit tests'

# Publish the web app as a build artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'
